name: main

on:
  push:
    branches: [main]
jobs:
  phpcs:
    name : Check code
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check Code Standard
        run :
          npm install
          npm run lint
